### ISSUE TITLE
Standardize responses

### ISSUE THREAD

**Issue by silverAndroid** [BrandonDanis/FriendStagram-API#21]
We should decide on a format for errors and regular responses because we can't have different types of responses for every endpoint. 

On the Android side, it would be such a pain because I would actually have to create a class for every different type of response. Currently, it's fine because I have a response class that takes a model as a generic parameter. Another reason is for backwards-compatibility purposes, we should never assume that users will update the application.

**Comment by BrandonDanis** [comment]
Agreed. Right now it's somewhat similar but we need a concrete 'template' for responses from the server. Take a look at this [structure](http://jsonapi.org/format/#document-structure) and let me know what you think.

**Comment by BrandonDanis** [comment]
Maybe something like this,
```
{
  "error": boolean,
  "data": {
    //data we requested
  },
  "errors": {
    //errors
  }
}
```
Check error to see if true/false, then grab info from `data` or `errors` accordingly

**Comment by silverAndroid** [comment]
And I assume when there are errors, `data` will be null

**Comment by BrandonDanis** [comment]
Yeah

**Comment by BrandonDanis** [comment]
I like the idea of [resource links](Invalid filename found in Content-Disposition header). 
Example: 
```
{
  "error": false,
  "data": {
    "username": "foo",
    "email": "foo@foo.com",
    "name": "Mr Foo",
    "links": {
      "self": {
        "href": "friendstagram.com/v1/users/foo"
      },
      "posts": {
        "href": "friendstagram.com/v1/posts/foo"
      },
      "followers": {
        "href": "friendstagram.com/v1/followers/foo"
      }
    }
  }
}
```
I know we currently return all the info about a user, including all posts, followers & following. But some endpoint could benefit from have these links associated with the response. That way you don't have to build the string yourself on the client side, it's provided already.

**Comment by silverAndroid** [comment]
I didn't quite understand the last bit about an endpoint benefiting from having the links associated with the response

**Comment by BrandonDanis** [comment]
Once you have the user info, and decide you want followers, you can simply to `request.get(res.data.links.followers.href)`

**Comment by silverAndroid** [comment]
Ohh I see, although I don't see why would we pass an href field since we know all the endpoints beforehand?

**Comment by BrandonDanis** [comment]
I think its more for other users of the service. Could be of convenience to someone who didn't write the endpoint :P

**Comment by BrandonDanis** [comment]
@jonathanGB I think we need your input

**Comment by jonathanGB** [comment]
Href is a good idea, follows the RESTful principles.

As for error, I'd remove the boolean and rely on whether errors array has a length > 0
