### ISSUE TITLE
Ability to follow users

### ISSUE THREAD

**Issue by BrandonDanis** [BrandonDanis/FriendStagram-API#5]
We need the ability to follow users, so the feed is only posts from those who your follow rather than every post on the app. 

I'll assign it to myself for now.

**Comment by jonathanGB** [comment]
+1

**Comment by jonathanGB** [comment]
We need to agree on a schema, like so:

* `users/:userId`: profile
* `users/:userId/posts`: posts from this user
* `/` : followers related posts
* `/trending`: trending/popular posts

What do you think?

**Comment by silverAndroid** [comment]
Would userId be user ID or username?

**Comment by BrandonDanis** [comment]
Maybe we should do `users/:username:` which would also return x number of recent posts? Cause I don't see myself needing just the the profile without wanting the posts.

And for followers posts, maybe `/feed`?

**Comment by jonathanGB** [comment]
`/` or `/feed` is ok with me

**Comment by silverAndroid** [comment]
I prefer /feed

**Comment by BrandonDanis** [comment]
@silverAndroid I think we are somewhat done with this?

**Comment by silverAndroid** [comment]
It seems to be done
